#Author: Christian Lockley
#Description: This program tells user if entered numbers equal numbers genrated by computer.
#This program also prints a game report every four turns and when user exits.
#Date: 9/29/2016
#Imports
import random;
#Declarations
run = True;
enteredNumber0 = 0;
enteredNumber1 = 0;
randomNumber0 = 0;
randomNumber1 = 0;
gamesPlayed = 0;
gamesWon = 0;

def getNumber():
    x = int(input("Enter a number greater than 0 and less than 21 or enter -1 to quit: "));
    while (x <= 0 or x >= 21) and x != -1:
        x = int(input("Invalid input please try again: "));
    return x;

def printReport(x, y):
    print("\n___________________________________\n");
    print("Game report:");
    print("Games played: ", x);
    print("Games won: ", y);
    #Caluations
    print("Games lost: ", x - y);
    print("\n___________________________________\n");

#Input
while run == True:
    randomNumber0 = random.randint(1, 20);
    randomNumber1 = random.randint(1, 20);
    #DEBUG
    #print(randomNumber0,randomNumber1);
    #ENDEBUG
    enteredNumber0 = getNumber();

    if (enteredNumber0 == -1):
        run = False;
        break;

    enteredNumber1 = getNumber();

    if (enteredNumber1 == -1):
        run = False;
        break;
#Output
   #Caluations
    if ((randomNumber0 == enteredNumber0 or randomNumber0 == enteredNumber1) and (randomNumber1 == enteredNumber1 or randomNumber1 == enteredNumber0)):
        print("Your chosen numbers match the ones generated by the random number generator");
        gamesWon += 1;
    else:
        print("The correct numbers are: ",randomNumber0," and ",randomNumber1);

    gamesPlayed += 1;
    
    print("\n___________________________________\n");

    if (gamesPlayed % 4 == 0):
            printReport(gamesPlayed, gamesWon);
if (gamesPlayed != 0 and ((gamesPlayed - 1) % 4) == 0): #Don't print consecutive reports
    printReport(gamesPlayed, gamesWon);
    input("Please type enter key to exit");
